spring:
  application:
    name: project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HT_AM
    username: root
    password: 
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
custom:
  file:
    dir: D:/nayoon/upload
server:
  port: 8081